name: Apply Infrastructure

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      gcp_provider_name:
        required: true
      gcp_sa:
        required: true
jobs:
  apply-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    steps:
      - name: Applying iac on ${{ inputs.env }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      
      - name: Terraform Format - ${{ inputs.env }} Environment
        id: fmt
        working-directory: ./infra/
        run: terraform fmt -recursive -check -diff
        continue-on-error: true

      - name: GCP Authentication
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_SA }}

      - name: Initialize project
        working-directory: ./infra/
        run: terraform init -backend-config=env/${{ inputs.env }}/backend.hcl  -var-file=env/${{ inputs.env }}/${{ inputs.env }}.tfvars -reconfigure

      - name: Terraform Plan - ${{ inputs.env }}
        working-directory: ./infra/
        run: terraform plan -var-file=env/${{ inputs.env }}/${{ inputs.env }}.tfvars -out=tfplan

      - name: Apply Infra - ${{ inputs.env }}
        working-directory: ./infra/
        id: apply_infra
        run: terraform apply -auto-approve tfplan
