name: Continuous Delivery

on:
  release:
    types: [published]
  push:
    branches: [master]

jobs:
  deploy-dev-app:
    name: deploy the DEV app
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy-app.yml
    with:
      env: dev
    secrets:
      app_id_github: ${{ secrets.APP_ID_GITHUB }}
      pr_author: ${{ secrets.PR_AUTHOR }}
      project_number: ${{ secrets.PROJECT_NUMBER_GITHUB_DEV }}
      column_name: ${{ secrets.COLUMN_NAME_GITHUB_DEV }}
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      gcp_app_key: ${{ secrets.GCP_APP_KEY_DEV }}
      gcp_webhook_secret: ${{ secrets.GCP_WEBHOOK_SECRET_DEV }}

  deploy-prod-app:
    name: deploy the PROD app
    if: github.event_name == 'release'
    uses: ./.github/workflows/deploy-app.yml
    with:
      env: prod
    secrets:
      app_id_github: ${{ secrets.APP_ID_GITHUB }}
      pr_author: ${{ secrets.PR_AUTHOR }}
      project_number: ${{ secrets.PROJECT_NUMBER_GITHUB_PROD }}
      column_name: ${{ secrets.COLUMN_NAME_GITHUB_PROD }}
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      gcp_app_key: ${{ secrets.GCP_APP_KEY_PROD }}
      gcp_webhook_secret: ${{ secrets.GCP_WEBHOOK_SECRET_PROD }}
