name: Continuous Delivery

on:
  release:
    types: [published]
  push:
    branches: [master]
  pull_request:

jobs:
  deploy-dev-app:
    name: deploy the DEV app
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' && github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy-app.yml
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project-id: ${{ secrets.GCP_PROJECT_ID }}
      env: dev


  deploy-prod-app:
    name: deploy the PROD app
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' && github.event_name == 'release'
    uses: ./.github/workflows/deploy-app.yml
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project-id: ${{ secrets.GCP_PROJECT_ID }}
      env: prod
