name: Continuous Delivery

on:
  push:
    branches:
      - master
      - chore/deploy-refactoring-266

jobs:
  deploy-app-dev:
    name: deploy the app - Dev
    uses: ./.github/workflows/deploy-app.yml
    with:
      env: dev
      app_id_github: ${{ vars.APP_ID_DEV }}
      pr_author: ${{ vars.PR_AUTHOR }}
      project_number: ${{ vars.PROJECT_NUMBER_DEV }}
      column_name: ${{ vars.COLUMN_NAME_DEV }}
      webhook_path: webhook-dev
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
    secrets:
      gcp_app_key: ${{ secrets.GCP_APP_KEY_DEV }}
      gcp_webhook_secret: ${{ secrets.GCP_WEBHOOK_SECRET_DEV }}
