name: Continuous Delivery

on:
  release:
    types: [published]
  push:
    branches: [master]

jobs:

  apply-infra-dev:
    name: Update infra - Dev
    if: github.event_name == 'push'
    uses: ./.github/workflows/apply-infra.yml
    with:
      env: dev
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}

  deploy-app-dev:
    name: deploy the app - Dev
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy-app.yml
    needs: apply-infra-dev
    with:
      env: dev
      app_id_github: ${{ secrets.APP_ID_DEV }}
      pr_author: ${{ secrets.PR_AUTHOR }}
      project_number: ${{ secrets.PROJECT_NUMBER_DEV }}
      column_name: ${{ secrets.COLUMN_NAME_DEV }}
      webhook_path: webhook-dev
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      gcp_app_key: ${{ secrets.GCP_APP_KEY_DEV }}
      gcp_webhook_secret: ${{ secrets.GCP_WEBHOOK_SECRET_DEV }}

  apply-infra-prod:
    name: Update infra - Prod
    if: github.event_name == 'release'
    uses: ./.github/workflows/apply-infra.yml
    with:
      env: prod
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}

  deploy-app-prod:
    name: deploy the app - Prod
    if: github.event_name == 'release'
    uses: ./.github/workflows/deploy-app.yml
    needs: apply-infra-prod
    with:
      env: prod
      app_id_github: ${{ vars.APP_ID_PROD }}
      pr_author: ${{ vars.PR_AUTHOR }}
      project_number: ${{ vars.PROJECT_NUMBER_PROD }}
      column_name: ${{ vars.COLUMN_NAME_PROD }}
      webhook_path: webhook-prod
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      gcp_app_key: ${{ secrets.GCP_APP_KEY_PROD }}
      gcp_webhook_secret: ${{ secrets.GCP_WEBHOOK_SECRET_PROD }}
