name: Continuous Delivery

on:
  release:
    types: [published]
  push:
    branches:
      - master
      - chore/deploy-refactoring-266

jobs:
  deploy-app-dev:
    name: deploy the app - Dev
    uses: ./.github/workflows/deploy-app.yml
    with:
      env: dev
      app_id_github: ${{ secrets.APP_ID_DEV }}
      pr_author: ${{ secrets.PR_AUTHOR }}
      project_number: ${{ secrets.PROJECT_NUMBER_DEV }}
      column_name: ${{ secrets.COLUMN_NAME_DEV }}
      webhook_path: webhook-dev
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      gcp_app_key: ${{ secrets.GCP_APP_KEY_DEV }}
      gcp_webhook_secret: ${{ secrets.GCP_WEBHOOK_SECRET_DEV }}
