name: Continuous Delivery

on:
  release:
    types: [published]
  push:
    branches: [master,47-improve-application-deployment-approach]

jobs:

  apply-infra-dev:
    name: Update infra - Dev
    if: github.event_name == 'push'
    uses: ./.github/workflows/apply-infra.yml
    with:
      env: dev

  deploy-app-dev:
    name: deploy the app
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy-app.yml
    needs: apply-infra-dev
    with:
      env: dev
    secrets:
      app_id_github: ${{ secrets.APP_ID_GITHUB }}
      pr_author: ${{ secrets.PR_AUTHOR }}
      project_number: ${{ secrets.PROJECT_NUMBER_GITHUB_DEV }}
      column_name: ${{ secrets.COLUMN_NAME_GITHUB_DEV }}
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project_id: ${{ secrets.GCP_PROJECT_ID }}

  apply-infra-prod:
    name: Update infra - Prod
    if: github.event_name == 'release'
    uses: ./.github/workflows/apply-infra.yml
    with:
      env: prod

  deploy-app-prod:
    name: deploy the app
    if: github.event_name == 'release'
    uses: ./.github/workflows/deploy-app.yml
    needs: apply-infra-prod
    with:
      env: prod
    secrets:
      app_id_github: ${{ secrets.APP_ID_GITHUB }}
      pr_author: ${{ secrets.PR_AUTHOR }}
      project_number: ${{ secrets.PROJECT_NUMBER_GITHUB_PROD }}
      column_name: ${{ secrets.COLUMN_NAME_GITHUB_PROD }}
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project_id: ${{ secrets.GCP_PROJECT_ID }}