name: Continuous Delivery

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [master,force-dev-deploy]
  pull_request:

jobs:
  deploy-dev-app:
    name: deploy the DEV app
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/deploy-app.yml
    with:
      env: dev
      project_number: 20
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project_id: ${{ secrets.GCP_PROJECT_ID }}

  deploy-prod-app:
    name: deploy the PROD app
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' && github.event_name == 'release'
    uses: ./.github/workflows/deploy-app.yml
    with:
      env: prod
      project_number: 20
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa: ${{ secrets.GCP_SA }}
      project_id: ${{ secrets.GCP_PROJECT_ID }}
