name: Continuous Integration

on:
  push:
    branches: [master, fix-terraform-lint]
  pull_request:

jobs:
  test-infra:
    name: Test terraform code
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    steps:
      - name: Checkout terraform code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.7
          terraform_wrapper: false
      
      - name: Terraform Format
        id: fmt
        working-directory: ./infra/
        run: terraform fmt -recursive -check -diff
        continue-on-error: true
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm ci
          npm run lint
          npm test

  automerge:
    name: Merge dependabot's PRs
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.github_token }}

