name: Continuous Integration

on: 
  push:
   branches:
    - master
  pull_request:

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm ci
          npm run lint
          npm test

  automerge:
    name: Merge dependabot's PRs
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.github_token }}


  deploy-app:
    name: deploy the app
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/deploy-app.yml
    secrets:
      project-id: ${{ secrets.GCP_PROJECT_ID }}
      target: techbase-staging
      graphql-api: ${{ needs.build-pr-infra.outputs.hasura_endpoint }}/v1/graphql
      firebase-config: ${{ secrets.VITE_FIREBASE_CONFIG_STAGING }}
      service-account-key: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TECHBASE }}'
