name: deploy-app

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

    secrets:
      app_id_github:
        required: true
      pr_author:
        required: true
      project_number:
        required: true
      column_name:
        required: true
      project_id:
        required: true
      gcp_provider_name:
        required: true
      gcp_sa:
        required: true
      gcp_webhook_secret:
        required: true
      gcp_app_key:
        required: true
      

jobs:
    deploy:
        name: Setup Gcloud Account
        permissions:
          id-token: write
          contents: read 
        runs-on: ubuntu-latest
        env:
          gcp_service_region: us-central1

        steps:
        - name: Deploy New App Version
          uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}

        - name: GCP Authentication
          id: auth
          uses: 'google-github-actions/auth@v0'
          with:
            token_format: 'access_token'
            workload_identity_provider: ${{ secrets.gcp_provider_name }}
            service_account: ${{ secrets.gcp_sa }}

        - name: Update the GPC Webhook Secrets
          run: |
            echo ${{ secrets.gcp_webhook_secret }} | gcloud secrets versions add unbreak_${{ inputs.env }}_webhook_secret --data-file=-
            gcloud secrets versions list unbreak_${{ inputs.env }}_webhook_secret |  sed '1d;2d' |awk '{print $1}' > versions_list_webhook
            for i in $(cat versions_list_webhook) ; do gcloud secrets versions destroy $i --secret=unbreak_${{ inputs.env }}_webhook_secret --quiet ; done
            
            
        - name: Update the GPC App Key Secrets
          run: |
            echo "${{ secrets.gcp_app_key }}" | gcloud secrets versions add unbreak_${{ inputs.env }}_app_key --data-file=-
            gcloud secrets versions list unbreak_${{ inputs.env }}_app_key |  sed '1d;2d' |awk '{print $1}' > versions_list_app
            for i in $(cat versions_list_app) ; do gcloud secrets versions destroy $i --secret=unbreak_${{ inputs.env }}_app_key --quiet ; done            

        - name: Deploy Docker image
          uses: 'google-github-actions/deploy-cloudrun@v0'
          with:
            service: 'unbreakci-${{ inputs.env }}'
            region: ${{ env.gcp_service_region }}
            project_id: ${{ env.project_id }}
            flags: --allow-unauthenticated
            suffix: ${{ github.sha }}
            source: .
            env_vars: |
              APP_ID_GITHUB=${{ secrets.app_id_github }}
              PR_AUTHOR=${{ secrets.pr_author }}
              PROJECT_NUMBER=${{ secrets.project_number }}
              COLUMN_NAME=${{ secrets.column_name }}
              LOG_LEVEL=info
            secrets: |
              WEBHOOK_SECRET=unbreak_${{ inputs.env }}_webhook_secret:latest
              APP_KEY=unbreak_${{ inputs.env }}_app_key:latest

