name: deploy-app

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      project_id:
        required: true
      gcp_provider_name:
        required: true
      gcp_sa:
        required: true
      

jobs:
    deploy:
        name: Setup Gcloud Account
        permissions:
          id-token: write
          contents: read 
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.project_id }}/unbreakci-${{ inputs.env }}:${{ github.sha }}
          REGION: us-central1

        steps:

        - name: GCP Authentication
          id: auth
          uses: 'google-github-actions/auth@v0'
          with:
            token_format: 'access_token'
            workload_identity_provider: ${{ secrets.gcp_provider_name }}
            service_account: ${{ secrets.gcp_sa }}

        - name: Login to GCR
          uses: docker/login-action@v2
          with:
            registry: gcr.io
            username: oauth2accesstoken
            password: ${{ steps.auth.outputs.access_token }}

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy New App version
          run: gcloud run deploy unbreakci-${{ inputs.env }}  --image $IMAGE_NAME  --platform managed --project=${{ secrets.project_id }} --allow-unauthenticated --region $REGION
            

