name: deploy-app

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      project_id:
        required: true
      gcp_provider_name:
        required: true
      gcp_sa:
        required: true
      

jobs:
    deploy:
        name: Setup Gcloud Account
        permissions:
          id-token: write
          contents: read 
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.project_id }}/unbreakci-${{ inputs.env }}:${{ github.sha }}
        steps:

        - name: GCP Authentication
          uses: 'google-github-actions/auth@v0'
          with:
            token_format: 'access_token'
            workload_identity_provider: ${{ secrets.gcp_provider_name }}
            service_account: ${{ secrets.gcp_sa }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          uses: 'google-github-actions/deploy-cloudrun@v0'
          with:
            service: 'unbreakci-${{ inputs.env }}'
            image: $IMAGE_NAME
