name: deploy-app

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      project_number:
        required: true
        type: string
    secrets:
      project_id:
        required: true
      gcp_provider_name:
        required: true
      gcp_sa:
        required: true
      

jobs:
    deploy:
        name: Setup Gcloud Account
        permissions:
          id-token: write
          contents: read 
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.project_id }}/unbreakci-${{ inputs.env }}:${{ github.sha }}
          gcp_service_region: us-central1

        steps:
        - name: Deploy New App Version
          uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}

        - name: GCP Authentication
          id: auth
          uses: 'google-github-actions/auth@v0'
          with:
            token_format: 'access_token'
            workload_identity_provider: ${{ secrets.gcp_provider_name }}
            service_account: ${{ secrets.gcp_sa }}

        - name: Deploy Docker image
          uses: 'google-github-actions/deploy-cloudrun@v0'
          with:
            service: 'unbreakci-${{ inputs.env }}'
            region: ${{ env.gcp_service_region }}
            image: ${{ env.IMAGE_NAME }}
            project_id: ${{ env.project_id }}
            flags: --allow-unauthenticated
            suffix: ${{ github.sha }}
            source: .
            env_vars: |
              APP_ID=222015
              PR_AUTHOR=dependabot
              PROJECT_NUMBER=${{ inputs.project_number }}
              COLUMN_NAME=unbreakci, LOG_LEVEL=info
            secrets: |
              WEBHOOK_SECRET=unbreak_${{ inputs.env }}_webhook_secret
              APP_KEY=unbreak_${{ inputs.env }}_app_key

