name: Apply Infrastructure - DEV

on:
  push:
   branches:
    - master
  pull_request:
    

jobs:
  apply-dev-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    steps:
      - name: Applying iac on DEV
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      
      - name: Terraform Format - DEV Environment
        id: fmt
        working-directory: ./infra/
        run: terraform fmt -recursive -check -diff

      - name: GCP Authentication
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Initialize project
        working-directory: ./infra/
        run: terraform init -backend-config=env/dev/backend.hcl  -var-file=env/dev/dev.tfvars -reconfigure

      - name: Terraform Plan - DEV
        working-directory: ./infra/
        run: terraform plan -var-file=env/dev/dev.tfvars -out=tfplan

      - name: Apply Infra - DEV
        working-directory: ./infra/
        id: apply_infra
        run: terraform apply -var-file=env/dev/dev.tfvars -auto-approve tfplan
