name: Apply Infrastructure - PROD

on:
  release:
    types: [published]
    paths:
      - 'infra/**'

jobs:  
  apply-prod-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Applying iac on ${{ inputs.environment }} ${{ inputs.region }} [${{ env.working_dir }}]
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      
      - name: Terraform Format - PROD Environment
        id: fmt
        run: terraform fmt -recursive -check -diff

      - name: GCP Authentication
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      
      - name: Initialize project
        run: terraform init -backend-config=env/prod/backend.hcl  -var-file=env/prod/prod.tfvars -reconfigure

      - name: Terraform Plan - PROD
        run: terraform plan -var-file=env/prod/prod.tfvars -out=tfplan

      - name: Apply Infra - PROD
        id: apply_infra
        run: terraform plan -var-file=env/prod/prod.tfvars -auto-approve tfplan
