name: Update prod

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  apply-infra:
    name: apply prod infra
    uses: ./.github/workflows/iac-apply.yml
    with:
      env: prod

  deploy-app:
    name: deploy the prod app
    uses: ./.github/workflows/deploy-app.yml
    needs: apply-infra
    with:
      env: prod
    secrets: inherit