name: Update dev

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  apply-infra:
    name: apply dev infra
    uses: ./.github/workflows/iac-apply.yml
    with:
      env: dev

  deploy-app:
    name: deploy the dev app
    uses: ./.github/workflows/deploy-app.yml
    needs: apply-infra
    with:
      env: dev
    secrets: inherit