name: Update environment - infra and deployment

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  apply-infra:
    name: Update infra
    uses: ./.github/workflows/iac-apply.yml

  deploy-app:
    name: deploy the app
    uses: ./.github/workflows/deploy-app.yml
    needs: apply-infra
    secrets: inherit